# Generated by Django 4.1.7 on 2023-03-12 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_title', models.CharField(max_length=300, null=True, verbose_name='EN Title')),
                ('ru_title', models.CharField(max_length=300, null=True, verbose_name='RU Title')),
                ('az_title', models.CharField(max_length=300, null=True, verbose_name='AZ Title')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_title', models.CharField(max_length=300, null=True, verbose_name='EN Title')),
                ('ru_title', models.CharField(max_length=300, null=True, verbose_name='RU Title')),
                ('az_title', models.CharField(max_length=300, null=True, verbose_name='AZ Title')),
                ('amount', models.IntegerField(blank=True, default=0, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Price')),
                ('compound', models.TextField(verbose_name='Compound')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
